[project]
name = "odoo-addons-oca-timesheet"
version = "19.0.20260126.1"
dependencies = [
    "odoo-addon-hr_timesheet_task_stage==19.0.*",
    "odoo-addon-hr_timesheet_time_control==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
