[project]
name = "odoo-addons-oca-timesheet"
version = "19.0.20260520.0"
dependencies = [
    "odoo-addon-crm_timesheet==19.0.*",
    "odoo-addon-hr_employee_cost_history==19.0.*",
    "odoo-addon-hr_timesheet_autofill_project_off==19.0.*",
    "odoo-addon-hr_timesheet_begin_end==19.0.*",
    "odoo-addon-hr_timesheet_calendar==19.0.*",
    "odoo-addon-hr_timesheet_date_order_desc==19.0.*",
    "odoo-addon-hr_timesheet_day_week==19.0.*",
    "odoo-addon-hr_timesheet_editable_top==19.0.*",
    "odoo-addon-hr_timesheet_employee_analytic_tag==19.0.*",
    "odoo-addon-hr_timesheet_name_customer==19.0.*",
    "odoo-addon-hr_timesheet_portal==19.0.*",
    "odoo-addon-hr_timesheet_report==19.0.*",
    "odoo-addon-hr_timesheet_sheet==19.0.*",
    "odoo-addon-hr_timesheet_sheet_attendance==19.0.*",
    "odoo-addon-hr_timesheet_sheet_autodraft==19.0.*",
    "odoo-addon-hr_timesheet_sheet_policy_project_manager==19.0.*",
    "odoo-addon-hr_timesheet_sheet_warning==19.0.*",
    "odoo-addon-hr_timesheet_task_domain==19.0.*",
    "odoo-addon-hr_timesheet_task_required==19.0.*",
    "odoo-addon-hr_timesheet_task_stage==19.0.*",
    "odoo-addon-hr_timesheet_time_control_begin_end==19.0.*",
    "odoo-addon-hr_timesheet_time_type==19.0.*",
    "odoo-addon-hr_timesheet_type_non_billable==19.0.*",
    "odoo-addon-hr_timesheet_unusual_days==19.0.*",
    "odoo-addon-project_task_analytic_propagation==19.0.*",
    "odoo-addon-project_timesheet_holidays_dynamic_description==19.0.*",
    "odoo-addon-project_timesheet_holidays_editable==19.0.*",
    "odoo-addon-sale_timesheet_budget==19.0.*",
    "odoo-addon-sale_timesheet_invoice_link==19.0.*",
    "odoo-addon-sale_timesheet_line_exclude==19.0.*",
    "odoo-addon-sale_timesheet_rounded==19.0.*",
    "odoo-addon-sale_timesheet_timeline==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
