[project]
name = "odoo-addons-oca-timesheet"
version = "19.0.20260810.0"
dependencies = [
    "odoo-addon-crm_timesheet==19.0.*",
    "odoo-addon-hr_timesheet_autofill_project_off==19.0.*",
    "odoo-addon-hr_timesheet_begin_end==19.0.*",
    "odoo-addon-hr_timesheet_day_week==19.0.*",
    "odoo-addon-hr_timesheet_employee_analytic_tag==19.0.*",
    "odoo-addon-hr_timesheet_task_domain==19.0.*",
    "odoo-addon-hr_timesheet_task_required==19.0.*",
    "odoo-addon-hr_timesheet_task_stage==19.0.*",
    "odoo-addon-hr_timesheet_time_control==19.0.*",
    "odoo-addon-hr_timesheet_time_control_begin_end==19.0.*",
    "odoo-addon-project_task_analytic_propagation==19.0.*",
    "odoo-addon-project_timesheet_holidays_dynamic_description==19.0.*",
    "odoo-addon-sale_order_update_timesheet_price==19.0.*",
    "odoo-addon-sale_timesheet_invoice_link==19.0.*",
    "odoo-addon-sale_timesheet_line_exclude==19.0.*",
    "odoo-addon-sale_timesheet_timeline==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
